### PR TITLE
Add JSX and ES6 support with Babel

### PR DESCRIPTION
**Pull request by ThibWeb**
That's a bigger change, to say the least.

I added Babel to the project to support JSX and ES6 in the solution. There are a few caveats to that:

- Right now Babel is used on the whole project and not just the solutions. It means that I had to change some of the project's code, because Babel uses strict mode by default, which caused some global variables to break.
- I updated React to the latest version, which is split into two packages and introduces some API changes. This version is only a release candidate at the moment.
- React's API has changed quite a lot, and we cannot switch transparently between non-JSX and JSX components anymore. Details are here https://gist.github.com/sebmarkbage/ae327f2eda03bf165261. This PR doesn't support non-JSX components at the moment, but I think that it could be added back with a bit more work.
- `workshopper`'s syntax highlighter doesn't support ES6 / JSX at the moment. I think this is coming, but not sure when (see https://github.com/workshopper/workshopper/issues/95).

Last but not least: I haven't updated some of the content in the problem descriptions (like "Here is what a really basic React component looks like (JSX syntax is optional, I prefer not to use it).") :p I guess it'll have to be changed depending on what you want to do with this PR :)

PS: if you want to give it a try, you can `npm install -g ThibWeb/thinking-in-react`. It will grab the latest version on GitHub, which _should_ work and may also contain more things than this PR.

### CODE REVIEW

**Comment by asbjornenge** [comment]
This is friggin fantastic :heart_eyes: It has been on my TODO list for 6 months I think :stuck_out_tongue: 

After writing this workshopper I have switched to using and :heart: JSX, so I'll def. merge this! I'll give it a try from your private module and update any relevant texts.

Thanks again! :rocket:

**Comment by asbjornenge** [comment]
I'm walking through the problem descriptions updating as I go :smile: I wondering as to why you haven't use `class` syntax for components?

**Comment by ThibWeb** [comment]
Good question! I've tried both syntaxes on my project and while I think that the `class` syntax looks cooler / is going to prevail in the future, I don't think it is the best right now.

[The 0.13 release post](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) details the differences between the two syntaxes. I'm not that keen on using ES7 feature proposals that are still at [stage 0/1](https://babeljs.io/docs/usage/experimental/), so without autobinding and property initializers the `class` syntax isn't nearly as convenient at the moment.

**Comment by asbjornenge** [comment]
Good points! I'll stick with your solutions :+1:

**Comment by asbjornenge** [comment]
It's out :tada: https://www.npmjs.com/package/thinking-in-react :rocket: 

Thanks again! Awesome work :grin:

**Comment by ThibWeb** [comment]
Amazing :) Have you thought of submitting a PR to include it on http://nodeschool.io/? I think it deserves a spot there.

**Comment by asbjornenge** [comment]
Oh, I should... I'm a bit swamped at work, but I'll try to get to it this evening :smile: If you have some time and want to do it, be my guest :see_no_evil: :grimacing: :+1:

**Comment by ThibWeb** [comment]
Haha consider it done!

**Comment by asbjornenge** [comment]
:rocket: Thanks a bunch!! :bow: :bowtie:

**Comment by ThibWeb** [comment]
Done :) https://github.com/nodeschool/nodeschool.github.io/pull/413 Let's see what happens.

Thanks for creating this workshopper by the way, my coworkers were all very happy when we did it together.

**Comment by asbjornenge** [comment]
Happy to hear it :grin: :clap: 

Thanks again for the PR and all your help :heart_eyes_cat:

**Pull request merged**
